apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/issuer: letsencrypt-dns
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    app: kiali
  name: kiali
spec:
  rules:
    - host: {{ .Values.istioDomain }}
      http:
        paths:
          - backend:
              serviceName: kiali
              servicePort: 20001
            path: /kiali
  tls:
    - hosts:
        - {{ .Values.istioDomain }}
      secretName: istio-ingress-tls
