apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ Values.namespace }}-certificate
  namespace: istio-system
spec:
  acme:
    config:
    - domains:
      - {{ Values.namespace }}.lead.{{ Values.account }}.liatr.io
      - *.{{ Values.namespace }}.lead.{{ Values.account }}.liatr.io
      dns01:
        provider: route53-liatrio
    commonName: {{ Values.namespace }}.lead.{{ Values.account }}.liatr.io
  dnsNames:
  - {{ Values.namespace }}.lead.{{ Values.account }}.liatr.io
  - *.{{ Values.namespace }}.lead.{{ Values.account }}.liatr.io
  issuerRef:
    kind: Issuer
    name: letsencrypt-dns
  secretName: {{ Values.namespace }}-certificate

